package modelo;
// Generated 26/09/2020 10:45:07 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vacuna generated by hbm2java
 */
public class Vacuna  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String descripcion;
     private Set dosises = new HashSet(0);

    public Vacuna() {
    }

    

	
    public Vacuna(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
   
    public Vacuna(int id, String nombre, String descripcion) {
        this.id = id;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Vacuna(int id, String nombre, String descripcion, Set dosises) {
       this.id = id;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.dosises = dosises;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getDosises() {
        return this.dosises;
    }
    
    public void setDosises(Set dosises) {
        this.dosises = dosises;
    }

    @Override
    public String toString() {
        return "Vacuna{" + "id=" + id + ", nombre=" + nombre + ", descripcion=" + descripcion + ", dosises=" + dosises + '}';
    }




}


